//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wilson6.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_FORMVIEW_CIRCLE             101
#define IDD_DLGBAR                      102
#define IDD_PROP1                       107
#define IDR_MAINFRAME                   128
#define IDR_WILSONTYPE                  129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDR_TOOLBAR1                    136
#define IDI_ICON3                       138
#define IDI_ICON4                       140
#define IDI_ICON5                       142
#define IDI_ICON6                       143
#define IDI_ICON7                       144
#define IDI_ICON8                       147
#define IDI_ICON10                      149
#define IDI_ICON11                      150
#define IDI_ICON12                      151
#define IDI_ICON13                      152
#define IDI_ICON14                      155
#define IDI_ICON9                       156
#define IDI_ICON15                      157
#define IDI_ICON16                      158
#define IDB_BITMAP1                     160
#define IDB_BITMAP2                     161
#define IDI_ICON17                      163
#define IDI_ICON18                      164
#define IDB_BITMAP3                     170
#define IDB_BITMAP4                     172
#define IDR_TOOLBAR2                    173
#define IDB_TREE_CLOSED                 177
#define IDB_TREE_OPENED                 178
#define IDD_FILETREE_DIALOG             179
#define IDI_BIAO                        180
#define IDI_RDS                         180
#define IDR_TOOLBAR3                    181
#define IDR_TOOLBAR4                    185
#define IDB_BITMAP5                     187
#define IDB_BITMAP6                     188
#define IDB_BITMAP7                     189
#define IDB_BITMAP8                     190
#define IDB_STOP                        190
#define IDB_BITMAP9                     191
#define IDB_BITMAP10                    192
#define IDB_BITMAP11                    193
#define IDB_BITMAP12                    194
#define IDB_BITMAP13                    195
#define IDB_ZhuZHOU                     195
#define IDR_TOOLBAR5                    196
#define IDI_ICON19                      198
#define IDI_ICON20                      204
#define IDI_ICON21                      206
#define IDR_MENU1                       207
#define IDC_CURSOR1                     208
#define IDI_ICON22                      209
#define IDI_ICON23                      210
#define IDI_ICON24                      211
#define IDC_CURSOR2                     212
#define IDC_CURSOR3                     213
#define IDC_CURSOR4                     214
#define IDC_CURSOR5                     215
#define IDC_CURSOR6                     216
#define IDB_DENGLU1                     218
#define IDD_DIALOGPWD                   220
#define IDD_DIALOG_PWD                  220
#define IDI_CYD                         221
#define IDD_FORMVIEW1                   221
#define IDD_FORMVIEW_POSITION           221
#define IDI_PIST                        222
#define IDD_PROP2                       222
#define IDI_FOLDER                      223
#define IDD_PROP3                       223
#define IDD_PROP4                       230
#define IDD_PAGE1                       231
#define IDD_PAGEFILTER                  231
#define IDD_PAGE2                       232
#define IDD_PAGEPROALG                  232
#define IDD_PROPERTY_DIALOG             233
#define IDD_PAGE3                       234
#define IDD_PAGEPARA_G                  234
#define IDD_PAGE4                       235
#define IDD_PAGEINOROUTCIRCLE           235
#define IDB_TIAOPING                    240
#define IDB_TIAOXIN                     241
#define IDB_RESET                       242
#define IDB_TIAOPINGXIN                 243
#define IDI_ICON25                      244
#define IDI_ICON26                      245
#define IDI_ICON27                      246
#define IDI_ICON28                      247
#define IDB_BITMAP14                    249
#define IDB_BITMAP15                    250
#define IDB_BITMAP16                    251
#define IDB_BITMAP17                    252
#define IDI_ICON31                      255
#define IDI_Enable                      259
#define IDI_DisEnable                   260
#define IDI_ICON29                      261
#define IDI_chuli                       262
#define IDI_Disable                     263
#define IDD_FORMVIEW2                   264
#define IDD_FORMVIEW_CYLINDER           264
#define IDD_DIALOGAJUSTCENTER           265
#define IDD_DIALOGADJUSTCENTER          265
#define IDD_DIALOG_AdjustCenter         265
#define IDD_PAGETARGETECCENTRICITY      266
#define IDD_PAGETIMES                   267
#define IDD_DIALOGADJUSTCENTERANDPOSE   268
#define IDD_DIALOG_AdjustCenterAndPose  268
#define IDD_PAGEHEIGHT                  269
#define IDD_DIALOGONEAXISPARA           270
#define IDD_PAGEEDIT                    271
#define IDI_ICONGO                      273
#define IDB_CHUANGANQI                  275
#define IDB_R                           276
#define IDB_LIZHU                       277
#define IDB_PINGTAI                     278
#define IDI_ZXD                         280
#define IDD_FORMVIEW3                   281
#define IDD_FORMVIEW_STRAIGHTNESS       281
#define IDI_SETORIGIN                   282
#define IDI_SETOTHERS                   283
#define IDI_Lineanalysis                284
#define IDI_Linenoselect                285
#define IDI_Lineselect                  286
#define IDI_PXD                         287
#define IDD_FORMVIEW4                   288
#define IDD_FORMVIEW_PARALLELISM        288
#define IDI_PMD                         289
#define IDD_FORMVIEW5                   290
#define IDD_FORMVIEW_PLANENESS          290
#define IDI_ResetDeal                   291
#define IDI_RotCyl                      292
#define IDI_tleft                       293
#define IDI_tright                      294
#define IDD_DIALOG1                     295
#define IDB_BITMAP18                    296
#define IDD_DlAlogCYAnalysis            299
#define IDI_YZDJMEnable                 300
#define IDI_YZDJMDisable                301
#define IDI_YZDJMchuli                  302
#define IDI_YZDJMResetDeal              303
#define IDI_OKJM                        306
#define IDI_CancleJM                    307
#define IDI_DELETE                      308
#define IDI_FenDuanChuLi                309
#define IDI_yuanduchuli                 328
#define IDD_DIALOG_EXTEND               329
#define IDB_BITMAP20                    331
#define IDI_CZD                         332
#define IDI_TXD                         333
#define IDI_TZD                         334
#define IDD_FORMVIEW6                   335
#define IDD_FORMVIEW_CONCENTRICITY      335
#define IDD_FORMVIEW7                   336
#define IDD_FORMVIEW_COAXIALITY         336
#define IDD_FORMVIEW8                   337
#define IDD_FORMVIEW_VERTICALITY        337
#define IDD_DIALOG2                     338
#define IDB_CHUANGANQI2                 339
#define IDB_PINGTAI2                    340
#define IDB_LIZHU2                      341
#define IDB_R2                          342
#define IDB_BITMAP19                    347
#define IDI_CRT                         348
#define IDI_TRT                         350
#define IDD_FORMVIEW9                   351
#define IDD_FORMVIEW_CircleRunOut       351
#define IDD_FORMVIEW10                  352
#define IDD_FORMVIEW_TOTALRUNOUT        352
#define IDI_BGFX                        353
#define IDI_PPFX                        354
#define IDD_FORMVIEW_JMANALYSE          356
#define IDD_DIALOG_CanShuChuLi          357
#define IDD_FORMVIEW_AdjustPosition     359
#define IDD_FORMVIEW_AdjustOritation    360
#define IDD_DIALOG_Frequency            362
#define IDD_DIALOGAJUSTPINGJING         363
#define IDD_DIALOGADJUSTPINGJING        363
#define IDD_DIALOG_AdjustPingjing       363
#define IDB_BITMAP21                    364
#define IDB_BITMAP22                    365
#define IDD_MOTORSTATE                  366
#define IDD_MOTORCORRECTION             367
#define IDD_DIALOG_YD                   370
#define IDD_DIALOG_YZD                  371
#define IDD_DIALOG_ZXD                  372
#define IDD_DIALOG_PMD                  373
#define IDD_DIALOG_PXD                  374
#define IDD_DIALOG_TZD                  375
#define IDD_DIALOG_TXD                  376
#define IDD_DIALOG_CZD                  377
#define IDD_DIALOG_USERMANAGEMENT       379
#define IDD_DIALOG_GONGYISETTING        380
#define IDD_PAGESELECT                  381
#define IDD_DIALOGONEAXISPARA1          382
#define IDD_DIALOG_ONEAXISPARA1         382
#define IDD_DIALOGHANDS                 383
#define IDD_DIALOG_HANDS                383
#define IDD_FORMVIEW_DYNAMICDISPLAY     384
#define IDD_DIALOG_MACHINEINF           385
#define IDD_DIALOG_pmPXD                386
#define IDI_AmplifyScale                388
#define IDD_DIALOG_AmpScale             391
#define IDD_DIALOG_zuobiao              392
#define IDD_FORMVIEW_DESKTOP            393
#define IDB_BITMAP_desktop              394
#define IDD_DIALOG_QK                   395
#define IDD_DIALOG_QKxs                 396
#define IDD_DIALOG_BiaoDing             397
#define IDD_DIALOG_SavePath             398
#define IDI_ICON30                      400
#define IDI_BTNTSTOP                    401
#define IDI_BTNTBEGIN                   402
#define IDC_BUTTON1                     1000
#define IDC_STOPALL                     1000
#define IDC_BUTTONSTART                 1000
#define IDC_SELECTBUTTON                1000
#define IDC_ClockRote                   1000
#define IDC_TLeft                       1000
#define IDC_DeletJM                     1000
#define IDC_FenDuanChuli                1000
#define IDC_CHULI                       1000
#define IDC_ToLeft                      1000
#define IDCHECK                         1000
#define IDC_apply                       1000
#define IDC_BTN_ADD                     1000
#define IDC_BUTTON_CHANGE               1000
#define IDC_CANCEL                      1001
#define IDC_BTN_DELETE                  1001
#define IDC_ChuanGQ                     1002
#define IDC_STATIC1                     1002
#define IDC_Chuanganqi                  1002
#define IDC_Picture                     1003
#define IDC_TREE1                       1005
#define IDC_BUTTON2                     1006
#define IDC_BUTTONANOTHER               1006
#define IDC_ANALYSISBUTTON              1006
#define IDC_Reset                       1006
#define IDC_TRight                      1006
#define IDC_QUIT                        1006
#define IDC_ToRight                     1006
#define IDC_EDIT3                       1007
#define IDC_EDIT4                       1008
#define IDC_EDIT5                       1009
#define IDC_STATIC2                     1011
#define IDC_Daogui                      1011
#define IDC_STATIC3                     1012
#define IDC_Lizhu                       1012
#define IDC_STATIC4                     1013
#define IDC_EDIT6                       1013
#define IDC_STATIC5                     1014
#define IDC_EDIT7                       1014
#define IDC_STATIC6                     1015
#define IDC_EDIT8                       1015
#define IDC_LIST1                       1016
#define IDC_EDIT11                      1016
#define IDC_LIST_HEIGHT                 1016
#define IDC_EDIT1                       1017
#define IDC_EDIT2                       1018
#define IDC_BUTTON22                    1019
#define IDC_EDITPRO2                    1019
#define IDC_EDIT12                      1019
#define IDC_EDIT13                      1020
#define IDC_EDIT14                      1021
#define IDC_EDIT15                      1022
#define IDC_EDIT16                      1023
#define IDC_EDIT_CZD                    1023
#define IDC_EDIT_INDENT                 1023
#define IDC_EDIT9                       1024
#define IDC_EDIT_INSPECTOR              1024
#define IDC_EDIT17                      1025
#define IDC_Deal_Circle                 1026
#define IDC_EDIT10                      1026
#define IDC_GoToPropSheet               1027
#define IDC_RADIO1                      1028
#define IDC_RADIOPRO1                   1028
#define IDC_RADIO2                      1029
#define IDC_RADIOPRO2                   1029
#define IDC_COMBO1                      1030
#define IDC_RADIO18                     1030
#define IDC_RADIO3                      1031
#define IDC_RADIOPRO3                   1031
#define IDC_RADIO4                      1032
#define IDC_RADIO5                      1033
#define IDC_RADIO19                     1033
#define IDC_RADIO6                      1034
#define IDC_RADIO7                      1035
#define IDC_RADIO8                      1036
#define IDC_STATI2                      1037
#define IDC_DataDeal                    1038
#define IDC_PROPERTY                    1039
#define IDC_EDITPRO1                    1040
#define IDC_EnAbleSelect                1040
#define IDC_EDITPRO3                    1041
#define IDC_EDITPRO4                    1042
#define IDC_TAB1                        1043
#define IDC_RADIO9                      1044
#define IDC_RADIO10                     1045
#define IDC_RADIO11                     1046
#define IDC_RADIO12                     1047
#define IDC_RADIO13                     1048
#define IDC_RADIO14                     1049
#define IDC_RADIO15                     1050
#define IDC_RADIO16                     1051
#define IDC_OK                          1052
#define IDC_AjustCenter                 1053
#define IDC_RADIO17                     1054
#define IDC_AjustLevel                  1055
#define IDC_SPIN1                       1055
#define IDC_HReset                      1056
#define IDC_Cylinder                    1056
#define IDC_AjustCenterAndLevel         1057
#define IDC_STATICCylinder              1057
#define IDC_EDIT18                      1058
#define IDC_EDIT19                      1059
#define IDC_CIRCEL                      1062
#define IDC_POSITION                    1063
#define IDC_LINE_STATIC                 1064
#define IDC_resetzxd                    1065
#define IDC_resetpxd                    1066
#define IDC_PARALLEL_STATIC             1067
#define IDC_YZDJM                       1068
#define IDC_Planeness                   1070
#define IDC_STARTPOSITION               1071
#define IDC_ENDPOSITION                 1072
#define IDC_OK_SAVE                     1073
#define IDC_SPLITNUMBER                 1074
#define IDC_Static_Concentricity        1075
#define IDC_STATIC_Coaxiality           1078
#define IDC_Verticality                 1082
#define IDC_STATICDEAL                  1084
#define IDC_STATICTotalDEAL             1085
#define IDC_JManalyse                   1086
#define IDC_AdjustPosition              1088
#define IDC_STATIC7                     1088
#define IDC_STATIC_AdjustOritation      1089
#define IDC_STATIC8                     1089
#define IDC_STATIC9                     1090
#define IDC_UNITTEXT                    1091
#define IDC_STATIC10                    1091
#define IDC_NAMETEXT                    1092
#define IDC_STATIC11                    1092
#define IDC_STATIC12                    1093
#define IDC_COMBO2                      1094
#define IDC_STATIC13                    1094
#define IDC_STATIC14                    1095
#define IDC_STATIC15                    1096
#define IDC_EDIT_YZD_H                  1096
#define IDC_STATIC16                    1097
#define IDC_EDIT_YZD_Num                1097
#define IDC_STATIC17                    1098
#define IDC_EDIT_YZD_Name               1098
#define IDC_STATIC18                    1099
#define IDC_EDIT_ZXD_H                  1099
#define IDC_EDIT_YZD_H2                 1099
#define IDC_EDIT_ZXD_Name               1100
#define IDC_EDIT_ZXD_V                  1100
#define IDC_EDIT_CZD_Name               1101
#define IDC_EDIT_ZXD_Name2              1101
#define IDC_EDIT_PMD_Name               1102
#define IDC_EDIT_PXD_Name               1103
#define IDC_EDIT_TXD_Name               1104
#define IDC_EDIT_TZD_Name               1105
#define IDC_EDIT_TZD_H                  1106
#define IDC_EDIT_TZD_H2                 1107
#define IDC_EDIT_CZD_H                  1108
#define IDC_EDIT_CZD_H2                 1109
#define IDC_EDIT_PXD_H                  1110
#define IDC_EDIT_PXD_V                  1111
#define IDC_EDITOLDUSENAME              1112
#define IDC_EDITOLDPWD                  1113
#define IDC_EDITNEWNAME                 1114
#define IDC_EDITNEWPWD                  1115
#define IDC_EDIT_STDVALUE               1116
#define IDC_EDIT_MEAVALUE               1117
#define IDC_EDIT_YD                     1118
#define IDC_EDIT_YZD                    1119
#define IDC_EDIT_PMD                    1120
#define IDC_EDIT_ZXD                    1121
#define IDC_EDIT_PXD                    1122
#define IDC_EDIT_TZD                    1123
#define IDC_EDITPOSITION                1124
#define IDC_CHECK1                      1126
#define IDC_EDIT_TARGETECCENTRICITY     1127
#define IDC_CHECKBACK                   1127
#define IDC_EDIT_FASTMOVEDISTANCE       1128
#define IDC_EDIT_TIMES                  1129
#define IDC_EDIT_DISTANCE               1131
#define IDC_EDIT_LTARGETECCENTRICITY    1132
#define IDC_EDIT_HTARGETECCENTRICITY    1133
#define IDC_EDIT_HEIGHT                 1134
#define IDC_editDynamicDisplay          1136
#define IDC_EDIT_OPERATORNAME           1137
#define DC_EDIT_MACHINEMODEL            1138
#define IDC_EDIT_MACHINENAME            1139
#define IDC_EDIT_PROCESS                1140
#define IDC_EDIT_WORKPIECEMODEL         1141
#define IDC_EDIT_WORKPIECENUM           1142
#define IDC_RADIO_SELECT                1143
#define IDC_EDIT_COMPANYNAME            1143
#define IDC_BUTTONOPENDYN               1147
#define IDC_BUTTONSTOPDYN               1148
#define IDC_EDIT_TZD_Num                1149
#define IDC_EDIT_CZD_Num                1150
#define IDC_STATIC_CircleRunOut         1151
#define IDC_EDIT_pmPXD_Name             1152
#define IDC_EDIT_pmPXD_H                1153
#define IDC_EDIT_Daogui                 1154
#define IDC_EDIT_Lizhu                  1155
#define IDC_DGXISHU                     1156
#define IDC_LZXISHU                     1157
#define ID_UnConnect                    32776
#define ID_Connect                      32777
#define ID_Print                        32779
#define ID_DoCircle                     32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_1                            32784
#define ID_2                            32785
#define ID_3                            32786
#define ID_4                            32787
#define ID_5                            32788
#define ID_6                            32789
#define ID_7                            32790
#define ID_8                            32791
#define ID_9                            32792
#define ID_SETTING                      32792
#define ID_MENUITEM32793                32793
#define ID_Combox                       32796
#define ID_20                           32797
#define ID_21                           32798
#define ID_22                           32799
#define ID_D                            32800
#define IDC_D                           32800
#define IDC_2                           32801
#define IDC_GOWORK                      32801
#define ID_TIAOPING                     32806
#define ID_TIAOXIN                      32807
#define ID_TIAOPINGTX                   32808
#define ID_RESET                        32809
#define ID_STOP                         32810
#define ID_LIZHU_UP                     32811
#define ID_LIZHU_DOWN                   32812
#define ID_DAOGUI_LEFT                  32813
#define ID_DAOGUI_RIGHT                 32814
#define ID_SENSOR_SIDE                  32815
#define ID_SENSOR_DOWN                  32816
#define ID_MAINSHAFT_ANTICLOCKWISE      32817
#define ID_MAINSHAFT_CLOCKWISE          32818
#define ID_PINGTAI_XF                   32819
#define ID_PINGTAI_XB                   32820
#define ID_PINGTAI_YL                   32821
#define ID_PINGTAI_XR                   32822
#define ID_PINGTAI_YR                   32822
#define ID_USERSETTING                  32823
#define ID_CAIJIANDCHULI                32824
#define ID_RESOURCEMANAGEMENT           32825
#define ID_DoCylinder                   32826
#define ID_DoPosition                   32828
#define ID_WORKPATHSETTING              32829
#define ID_DoStraightness               32830
#define ID_MENUITEM32831                32831
#define ID_DoParallelism                32832
#define ID_MENUITEM32833                32833
#define ID_DoPlaneness                  32834
#define ID_DAQ_CIRCLE_FORM              32835
#define ID_DAQ_CIRCLE_SEMIAU            32836
#define ID_DAQ_CIRCLE_REM               32837
#define ID_DAQ_CYD_SEMIAU               32838
#define ID_DAQ_CYD_FORM                 32839
#define ID_DAQ_CYD_REM                  32840
#define ID_DAQ_STRAIGHTNESS             32841
#define ID_DAQ_PLANENESS                32842
#define ID_DAQ_PARA                     32843
#define ID_DAQ_AXIALITY                 32844
#define ID_DAQ_SQUARENESS               32845
#define ID_STD_G1G2                     32846
#define ID_USER_GUIDE                   32847
#define ID_DOCONCENTRICITY              32848
#define ID_DOCOAXIALITY                 32849
#define ID_DOVERTICALITY                32850
#define ID_BTNCHULI                     32851
#define ID_BTNDISABLE                   32852
#define ID_BTNENABLE                    32853
#define ID_BTNSETORIGIN                 32854
#define ID_BTNSETOTHERS                 32855
#define ID_BTNTLEFT                     32857
#define ID_BTNTRIGHT                    32858
#define ID_BTNFENDUANCHULI              32859
#define ID_BTNRESETDEAL                 32861
#define ID_BTNYUANDUCHULI               32863
#define ID_BTNBGFX                      32864
#define ID_BTNPPFX                      32865
#define ID_DOTOTALRUNOUT                32866
#define ID_DOCIRCLERUNOUT               32867
#define ID_BTNDELETE                    32868
#define ID_MOTORSTATE                   32869
#define ID_ZHITUIDIANJIFIRST_U          32870
#define ID_ZHITUIDIANJIFIRST_D          32871
#define ID_ZHITUIDIANJISECOND_U         32872
#define ID_ZHITUIDIANJISECOND_D         32873
#define ID_CANSHUCHUSHI                 32874
#define ID_AdjustPosition               32875
#define ID_AdjustOritation              32876
#define ID_MotorCorrect                 32877
#define ID_SET_FILE_SAVE_PATH           32878
#define ID_CHUGANQI_BIAODING            32879
#define ID_GONGYI_SETTING               32880
#define ID_HandVelocitySet              32881
#define ID_LIZHU_SETZERO                32883
#define ID_DAOGUI_SETZERO               32884
#define ID_DYNAMICDIPLAY                32885
#define ID_MACHINE_INF                  32886
#define ID_DAQ_pmPLANENESS              32887
#define ID_AmplifyScale                 32898
#define ID_shujucanshu                  32899
#define ID_ZUOBIAO_SET                  32900
#define ID_OUT                          32901
#define ID_AUTODELQK                    32903
#define ID_AUTOQKXS                     32904
#define ID_BTNTBEGIN                    32905
#define ID_BTNTSTOP                     32906
#define ID_LpPrint                      32907
#define ID_MENU_Lpxianshi               32908
#define IDC_MYTREECTRL                  61216
#define ID_fSTATE                       61217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1158
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
